spring:
  h2:
    console:
      path: /h2-multidatasource
      enabled: true

db1:
  datasource:
    url: jdbc:h2:file:~/test-db1
    username:
    password:
    driver-class-name: org.h2.Driver

db2:
  datasource:
    url: jdbc:h2:file:~/test-db2
    username:
    password:
    driver-class-name: org.h2.Driver

